In [2]:
import torch
import torch.nn as nn
import pandas as pd

In [3]:
df = pd.read_csv("diabetes.csv")

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
X = df.drop("Outcome",axis=1)

In [7]:
X.shape

(768, 8)

In [12]:
X_array = X.to_numpy()

In [13]:
X_array

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [15]:
# tensor expect data like numpy array, not additional metadata like col, indices
inputs = torch.tensor(data = X_array)

In [16]:
inputs

tensor([[  6.0000, 148.0000,  72.0000,  ...,  33.6000,   0.6270,  50.0000],
        [  1.0000,  85.0000,  66.0000,  ...,  26.6000,   0.3510,  31.0000],
        [  8.0000, 183.0000,  64.0000,  ...,  23.3000,   0.6720,  32.0000],
        ...,
        [  5.0000, 121.0000,  72.0000,  ...,  26.2000,   0.2450,  30.0000],
        [  1.0000, 126.0000,  60.0000,  ...,  30.1000,   0.3490,  47.0000],
        [  1.0000,  93.0000,  70.0000,  ...,  30.4000,   0.3150,  23.0000]],
       dtype=torch.float64)

In [24]:
model = nn.Sequential(
    nn.Linear(8,3,dtype = torch.float64), # need to specify, bceause default is dtype = torch.float32
    nn.Linear(3,1,dtype = torch.float64),
    nn.Sigmoid())

In [23]:
model(inputs)

tensor([[1.0000e+00],
        [9.9369e-01],
        [9.9985e-01],
        [3.0410e-04],
        [9.6819e-01],
        [2.5509e-01],
        [2.2234e-01],
        [1.0000e+00],
        [5.8822e-19],
        [8.8088e-05],
        [9.0368e-03],
        [9.9859e-01],
        [8.9044e-01],
        [1.6404e-35],
        [1.1329e-04],
        [1.0000e+00],
        [5.1251e-08],
        [1.4364e-01],
        [1.0000e+00],
        [8.3106e-02],
        [4.3376e-10],
        [8.1418e-02],
        [9.9917e-01],
        [9.8218e-01],
        [8.5579e-06],
        [1.9669e-03],
        [9.9708e-01],
        [2.4040e-07],
        [1.5210e-04],
        [2.2303e-02],
        [9.9989e-01],
        [2.0100e-08],
        [1.1572e-02],
        [1.5500e-05],
        [9.9670e-01],
        [4.5730e-07],
        [7.9549e-01],
        [9.9864e-01],
        [9.9989e-01],
        [2.1599e-05],
        [9.9960e-01],
        [7.2891e-01],
        [5.7484e-02],
        [4.0450e-11],
        [9.9972e-01],
        [1

In [25]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
optical_recognition_of_handwritten_digits = fetch_ucirepo(id=80) 
  
# data (as pandas dataframes) 
X = optical_recognition_of_handwritten_digits.data.features 

In [48]:
X

Attribute1  Attribute2  Attribute3  Attribute4  Attribute5  Attribute6  \
0              0           1           6          15          12           1   
1              0           0          10          16           6           0   
2              0           0           8          15          16          13   
3              0           0           0           3          11          16   
4              0           0           5          14           4           0   
...          ...         ...         ...         ...         ...         ...   
5615           0           0           4          10          13           6   
5616           0           0           6          16          13          11   
5617           0           0           1          11          15           1   
5618           0           0           2          10           7           0   
5619           0           0          10          14           8           1   

      Attribute7  Attribute8  Attribute9  Attribute10  ...  Attribute55  \
0              0           0           0            7  ...            0   
1              0           0           0            7  ...            3   
2              0           0           0            1  ...            0   
3              0           0           0            0  ...            0   
4              0           0           0            0  ...           12   
...          ...         ...         ...          ...  ...          ...   
5615           0           0           0            1  ...            4   
5616           1           0           0            0  ...            1   
5617           0           0           0            0  ...            0   
5618           0           0           0            0  ...            2   
5619           0           0           0            2  ...            8   

      Attribute56  Attribute57  Attribute58  Attribute59  Attribute60  \
0               0            0            0            6           14   
1               0            0            0           10           16   
2               0            0            0            9           14   
3               0            0            0            0            1   
4               0            0            0            4           12   
...           ...          ...          ...          ...          ...   
5615            0            0            0            2           14   
5616            0            0            0            6           16   
5617            0            0            0            2            9   
5618            0            0            0            5           12   
5619            0            0            1            8           12   

      Attribute61  Attribute62  Attribute63  Attribute64  
0               7            1            0            0  
1              15            3            0            0  
2               0            0            0            0  
3              15            2            0            0  
4              14            7            0            0  
...           ...          ...          ...          ...  
5615           15            9            0            0  
5616           14            6            0            0  
5617           13            6            0            0  
5618           16           12            0            0  
5619           14           12            1            0  

[5620 rows x 64 columns]

In [37]:
X_array = X.to_numpy(dtype = "float64")

In [39]:
X_array.dtype

dtype('float64')

In [47]:
X_array.shape

(5620, 64)

In [43]:
inputs = torch.tensor(X_array)

In [40]:
X.shape

(5620, 64)

In [45]:
model_multi = nn.Sequential(
    nn.Linear(64,30,dtype = torch.float64),
    nn.Linear(30,15,dtype = torch.float64),
    nn.Linear(15,10,dtype = torch.float64),
    nn.Softmax()
)

In [54]:
model_multi(inputs)

C:\Users\shiva\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1776: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.0326, 0.0083, 0.2645,  ..., 0.1810, 0.0144, 0.0330],
        [0.0174, 0.0120, 0.1749,  ..., 0.2240, 0.0191, 0.0394],
        [0.0166, 0.0156, 0.3131,  ..., 0.0517, 0.0092, 0.0118],
        ...,
        [0.0028, 0.0090, 0.4750,  ..., 0.0591, 0.0045, 0.1477],
        [0.0041, 0.0290, 0.0574,  ..., 0.3417, 0.0489, 0.2393],
        [0.0085, 0.0169, 0.3694,  ..., 0.0937, 0.0068, 0.1373]],
       dtype=torch.float64, grad_fn=<SoftmaxBackward0>)