In [1]:
import torch 
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 

In [3]:
X.shape, y.shape

((150, 4), (150, 1))

In [4]:
X_tensor = torch.tensor(X.to_numpy(),dtype = torch.float32,requires_grad=True)

In [5]:
y_boolean = LabelEncoder().fit_transform(y)


C:\Users\shiva\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
y_bol_ten = torch.tensor(y_boolean,dtype = torch.float32,requires_grad=True).long()

In [7]:
y_tensor = nn.functional.one_hot(y_bol_ten,num_classes=4)

In [37]:
y_tensor #print(#y_tensor) prints full tensors

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1.,

In [10]:
y_tensor = y_tensor.type(torch.float32)

In [11]:
y_tensor.shape

torch.Size([150, 4])

In [12]:
model = nn.Sequential(nn.Linear(4, 2),
                      nn.Linear(2, 4),
                      nn.ReLU()
                     )

In [13]:
model

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=4, bias=True)
  (2): ReLU()
)

In [14]:
y_prediction = model(X_tensor)

In [15]:
y_prediction

tensor([[2.8403e-01, 1.4617e-02, 8.9487e-01, 3.4345e-01],
        [2.8554e-01, 5.0991e-02, 8.8679e-01, 3.4150e-01],
        [2.9165e-01, 8.1664e-02, 8.6484e-01, 3.4886e-01],
        [3.0370e-01, 1.7142e-01, 8.1885e-01, 3.5955e-01],
        [2.8941e-01, 4.6389e-02, 8.7509e-01, 3.4931e-01],
        [2.8490e-01, 1.5927e-02, 8.9201e-01, 3.4490e-01],
        [2.9991e-01, 1.3561e-01, 8.3401e-01, 3.5717e-01],
        [2.9142e-01, 7.1498e-02, 8.6648e-01, 3.4977e-01],
        [3.0452e-01, 1.8657e-01, 8.1488e-01, 3.5909e-01],
        [2.9462e-01, 1.0232e-01, 8.5364e-01, 3.5169e-01],
        [2.7915e-01, 0.0000e+00, 9.1411e-01, 3.3999e-01],
        [3.0420e-01, 1.6015e-01, 8.1831e-01, 3.6195e-01],
        [2.9270e-01, 9.3461e-02, 8.6046e-01, 3.4927e-01],
        [2.9903e-01, 1.3430e-01, 8.3687e-01, 3.5572e-01],
        [2.5290e-01, 0.0000e+00, 1.0146e+00, 3.1712e-01],
        [2.7002e-01, 0.0000e+00, 9.5058e-01, 3.3421e-01],
        [2.6628e-01, 0.0000e+00, 9.6244e-01, 3.2744e-01],
        [2.809

In [16]:
y_prediction.shape == y_tensor.shape

True

In [17]:
loss_object = nn.CrossEntropyLoss()

In [18]:
loss = loss_object(y_prediction,y_tensor)

In [19]:
loss

tensor(1.3930, grad_fn=<DivBackward1>)

In [20]:
loss.backward() #Computes the gradient of current tensor wrt graph leaves.

In [21]:
wieght_0 = model[0].weight

In [22]:
wieght_0

Parameter containing:
tensor([[ 0.1542, -0.2685, -0.1396,  0.3999],
        [ 0.3517,  0.1862, -0.4546, -0.1201]], requires_grad=True)

In [23]:
wieght_0_grad = wieght_0.grad
wieght_0_grad

tensor([[ 0.0901,  0.1007, -0.1537, -0.1010],
        [ 0.1937,  0.1307, -0.0285, -0.0520]])

In [24]:
bias_0 = model[0].bias
bias_0

Parameter containing:
tensor([-0.1017, -0.2803], requires_grad=True)

In [25]:
bias_0_grad = bias_0.grad
bias_0_grad

tensor([0.0373, 0.0499])

In [26]:
lr = 0.1
bias_0 = bias_0 - lr*bias_0_grad

In [27]:
bias_0

tensor([-0.1054, -0.2853], grad_fn=<SubBackward0>)

In [28]:
## You cannot do manually for many layers and for each layer you have to update the many parameters
## PyTorch optimizers handle it all in just one line of code

In [29]:
optimizer = torch.optim.SGD(model.parameters(),lr = 0.1)

In [30]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [31]:
optimizer.step() #Perform a single optimization step.

In [32]:
# optimizer.zero_grad() #Prevents gradient accumulation from previous step.

In [33]:
y_pred_2 = model(X_tensor)

In [34]:
loss_2 = loss_object(y_pred_2,y_tensor)

In [35]:
loss_2

tensor(1.3546, grad_fn=<DivBackward1>)

In [44]:
loss_2.backward() ## compute new gradients

In [36]:
optimizer.step()