In [10]:
# import torch
import torch.nn as nn

In [2]:
num = [[2,3,4,5]]

In [4]:
t = torch.tensor(num)

In [19]:
t

tensor([[2, 3, 4, 5]])

In [40]:
t.dtype

torch.float32

In [44]:
t.shape

torch.Size([1, 4])

In [35]:
t = torch.tensor(t,dtype=torch.float32)

C:\Users\shiva\AppData\Local\Temp\ipykernel_9268\1296307948.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t = torch.tensor(t,dtype=torch.float32)


In [45]:
linear_ly  = nn.Linear(in_features=4,out_features=2,bias = True,dtype= torch.float32) 
#default dtype for nn.Linear is torch.float32
#usually float32, but your input is Long (int64)

In [46]:
linear_ly

Linear(in_features=4, out_features=2, bias=True)

In [47]:
linear_ly(t)

tensor([[1.0223, 0.0398]], grad_fn=<AddmmBackward0>)

In [50]:
linear_ly.bias

Parameter containing:
tensor([ 0.0166, -0.1384], requires_grad=True)

In [51]:
linear_ly.weight

Parameter containing:
tensor([[ 0.0065, -0.2728,  0.4926, -0.0318],
        [-0.3674,  0.1519,  0.3445, -0.1841]], requires_grad=True)

In [61]:
ly_3 = nn.Sequential(
    nn.Linear(4,2),
    nn.Linear(2,5),
    nn.Linear(5,7)
)

In [62]:
ly_3

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=5, bias=True)
  (2): Linear(in_features=5, out_features=7, bias=True)
)

In [63]:
ly_3(t)

tensor([[ 0.1369,  0.2524, -0.3470,  0.6467,  0.4119, -0.1783,  0.4052]],
       grad_fn=<AddmmBackward0>)

In [71]:
for i in ly_3.parameters():
    # k = i.numel()
    # print(k)
    print(i)

Parameter containing:
tensor([[ 0.3226, -0.1360,  0.3030, -0.0428],
        [ 0.4500, -0.1592,  0.1149,  0.0598]], requires_grad=True)
Parameter containing:
tensor([0.1688, 0.3218], requires_grad=True)
Parameter containing:
tensor([[ 0.1029,  0.1337],
        [-0.1956, -0.1821],
        [-0.0337, -0.3637],
        [-0.6209, -0.3425],
        [ 0.6786, -0.6741]], requires_grad=True)
Parameter containing:
tensor([-0.6527, -0.3591, -0.1481,  0.5721, -0.3074], requires_grad=True)
Parameter containing:
tensor([[-0.0321, -0.0765,  0.4268, -0.1182,  0.1424],
        [-0.3665, -0.0072,  0.2238, -0.1812,  0.2332],
        [ 0.1664, -0.1111,  0.2714,  0.0674,  0.0866],
        [ 0.2637, -0.1408, -0.3696, -0.4422,  0.1794],
        [ 0.0160, -0.3679, -0.1445, -0.2565, -0.2926],
        [ 0.3538,  0.0876, -0.2574, -0.1536,  0.2868],
        [-0.2286, -0.2146,  0.2744,  0.0892, -0.2017]], requires_grad=True)
Parameter containing:
tensor([ 0.3305,  0.2376, -0.1086,  0.0315, -0.3408, -0.2007,  0.3424

In [72]:
t

tensor([[2., 3., 4., 5.]])

In [74]:
s = nn.Sigmoid()

In [75]:
s(t)

tensor([[0.8808, 0.9526, 0.9820, 0.9933]])

In [78]:
soft = nn.Softmax(dim=-1)

In [80]:
soft(t)

tensor([[0.0321, 0.0871, 0.2369, 0.6439]])